"""
Environment file loader for django-env-doctor.

Loads .env files into os.environ without overwriting existing values.
Supports comments, quoted values, and multiline values.
"""

import os
import re
from pathlib import Path
from typing import Dict, Optional, Union


def load_env_file(
    filepath: Optional[Union[str, Path]] = None,
    override: bool = False,
    encoding: str = "utf-8",
) -> Dict[str, str]:
    """
    Load a .env file and populate os.environ.

    Args:
        filepath:  Path (str or Path) to the .env file. Defaults to '.env' in the current directory.
        override:  If True, existing env vars will be overwritten. Default False.
        encoding:  File encoding. Default utf-8.

    Returns:
        Dict of variables that were loaded from the file.
    """
    if filepath is None:
        filepath = os.path.join(os.getcwd(), ".env")

    path = Path(filepath)
    if not path.exists():
        return {}

    loaded = {}
    raw_content = path.read_text(encoding=encoding)
    parsed = _parse_env_content(raw_content)

    for key, value in parsed.items():
        if override or key not in os.environ:
            os.environ[key] = value
            loaded[key] = value

    return loaded


def _parse_env_content(content: str) -> Dict[str, str]:
    """
    Parse the content of a .env file into a dict.

    Handles:
    - Comments (lines starting with #)
    - Inline comments
    - Single and double quoted values
    - Multiline values with triple quotes
    - Export prefix (export KEY=VALUE)
    - Blank lines
    """
    result = {}
    lines = content.splitlines()
    i = 0

    while i < len(lines):
        line = lines[i].strip()
        i += 1

        # Skip blank lines and comments
        if not line or line.startswith("#"):
            continue

        # Strip optional 'export ' prefix
        if line.startswith("export "):
            line = line[7:].strip()

        # Must contain an = sign
        if "=" not in line:
            continue

        key, _, raw_value = line.partition("=")
        key = key.strip()

        if not _is_valid_key(key):
            continue

        # Handle triple-quoted multiline values
        if raw_value.startswith('"""') or raw_value.startswith("'''"):
            quote = raw_value[:3]
            raw_value = raw_value[3:]
            multiline_parts = [raw_value]
            while quote not in raw_value and i < len(lines):
                raw_value = lines[i]
                i += 1
                multiline_parts.append(raw_value)
            value = "\n".join(multiline_parts).rstrip(quote).strip()
        else:
            stripped_raw = raw_value.strip()
            is_quoted = len(stripped_raw) >= 2 and stripped_raw[0] in ('"', "'") and stripped_raw[-1] == stripped_raw[0]
            value = _unquote(stripped_raw)
            # Only strip inline comments for unquoted values; quoted values
            # may legitimately contain '#' characters.
            if not is_quoted:
                value = _strip_inline_comment(value)

        result[key] = value

    return result


def _is_valid_key(key: str) -> bool:
    return bool(re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", key))


def _unquote(value: str) -> str:
    """Remove surrounding quotes from a value."""
    if len(value) >= 2:
        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            return value[1:-1]
    return value


def _strip_inline_comment(value: str) -> str:
    """Remove inline comments (e.g. VALUE=foo  # this is a comment)."""
    # Only strip comments outside of quotes
    if value.startswith(('"', "'")):
        return value
    match = re.split(r"\s+#", value, maxsplit=1)
    return match[0].strip()


def generate_example_file(
    schema: dict,
    output_path: str = ".env.example",
    encoding: str = "utf-8",
) -> None:
    """
    Generate a .env.example file from the schema.

    Each variable is written with its type, requirement status,
    description, and a placeholder or default value.
    """
    lines = [
        "# .env.example",
        "# Auto-generated by django-env-doctor",
        "# Do NOT commit your actual .env file — only this example.",
        "",
    ]

    for name, var_schema in schema.items():
        # Add description comment
        if var_schema.description:
            lines.append(f"# {var_schema.description}")

        # Add metadata comment
        meta_parts = [f"type={var_schema.type.value}"]
        if var_schema.required and var_schema.default is None:
            meta_parts.append("required")
        else:
            meta_parts.append("optional")
        if var_schema.choices:
            meta_parts.append(f"choices={','.join(str(c) for c in var_schema.choices)}")

        lines.append(f"# [{', '.join(meta_parts)}]")

        # Add the variable with placeholder or default
        if var_schema.default is not None:
            lines.append(f"{name}={var_schema.default}")
        elif var_schema.secret:
            lines.append(f"{name}=your-secret-{name.lower().replace('_', '-')}")
        else:
            lines.append(f"{name}=")

        lines.append("")

    Path(output_path).write_text("\n".join(lines), encoding=encoding)
